import { PageHeading } from '@/components/page-heading';
import { PageInfoContainer } from '@/components/page-info-container';

export default function BarbequePolicyPage() {
  return (
    <>
      <PageHeading title="Barbeque Policy" />
      <PageInfoContainer>
        <div className="space-y-6">
          <p>
            AMSA recognizes that teams enjoy barbecuing at the field. AMSA
            supports barbecues, as long as they are managed responsibly. But
            trash and hot coals from barbecues have increasingly become a
            maintenance problem.
          </p>
          <p>The following guidelines will apply to barbecues from now on:</p>

          <ol className="pl-2 space-y-6 list-decimal list-inside">
            <li>
              Gas grills are preferred, to avoid problems from burning coals.
            </li>
            <li>If charcoal grills are used, teams must:</li>
            <ul className="pl-2 space-y-6 list-disc list-inside">
              <li>Douse all coals</li>
              <li>Remove the coals from the Complex.</li>
            </ul>
            <li>
              Teams must also remove all trash generated by the barbecue, to
              avoid overflowing trash cans at the fields.
            </li>
          </ol>

          <p>
            Teams who fail to douse and remove coals, or who fail to remove
            trash, will be penalized as follows:
          </p>
          <p>First offense: $50 fine.</p>
          <p>Second offense: Deduction of three (3) points in standings.</p>
        </div>
      </PageInfoContainer>
    </>
  );
}
